name: SQL Linter (Check Modified Schema)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  SQL_Linter_Check_Modified:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code in Repository
        uses: "actions/checkout@v3"
      - name: Start SQL Linter
        run: |
          pip install sqlfluff
          sqlfluff lint $GITHUB_WORKSPACE/DataSchemaModified.sql --dialect postgres
