name: Print Software Versions

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  PrintAppServerVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Java Version
        run: java --version

  PrintDBMSVersions:
    runs-on: ubuntu-latest
    needs: [PrintAppServerVersions]
    steps:
      - name: Print PostgreSQL Version
        run: psql --version
